### ISSUE TITLE
Using the VRFCoordinatorV2Mock fulfillRandomWords "random" words

### ISSUE THREAD

**Issue by morismc** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#22]
Maybe I missed that part, but I don't understand how the random number is being generated when it comes to testing the VRFCoordinatorV2Mock. 

@PatrickAlphaC How did you know that Account 2 was always picked? In my code it seems to be always Account 3. Can you please elaborate how to calculate the winner? Thanks for your support.

**Comment by morismc** [comment]
Hello Patrick, thanks for the info. I actually wanted to know why it is always accounts[2] which is drawn by the mock random generator. I can't find any line saying "take account 3 from the array and make it the winner". Can you please point me/us to the line where the "randum" number 2 is being generated? Thanks a lot.

**Comment by PatrickAlphaC** [comment]
We pick the winner here: https://github.com/PatrickAlphaC/hardhat-smartcontract-lottery-fcc/blob/235e5a45473c0f8530461c59eb8aac6284e98465/test/unit/Raffle.test.js#L184

Which calls this function: https://github.com/smartcontractkit/chainlink/blob/a8855531dc6f1d29a563efdc7e0e326b1aa1a886/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol#L99

Which isn't random (since we are just using a mock contract) and doing so always returns the same winner.
