### ISSUE TITLE
Cannot read properties of undefined (reading 'toNumber')

### ISSUE THREAD

**Issue by batuhankacmaz** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#23]
`it("updates the raffle state and emits a requestId", async () => {
                  // Too many asserts in this test!
                  await raffle.enterRaffle({ value: raffleEntranceFee })
                  await network.provider.send("evm_increaseTime", [interval + 1])
                  await network.provider.request({ method: "evm_mine", params: [] })
                  const txResponse = await raffle.performUpkeep([])
                  const txReceipt = await txResponse.wait(1)
                  const raffleState = await raffle.getRaffleState()
                  const requestId = txReceipt!.events![1].args!.requestId
                  assert(requestId.toNumber() > 0)
                  assert(raffleState == 1)
              })`

When I run the test txReceipt!.events![1].args!.requestId becomes undefined. how to I check inside of the txReceipt in the test folder

**Comment by batuhankacmaz** [comment]
I fixed the problem. In the raffleContract I made spelling mistake when I fix the problem is solved but I still wonder how can I debug the txReceipt?

**Comment by AVDel7** [comment]
I'm also had the same issue. As far as I understand, the [exclamation marks](https://stackoverflow.com/questions/42273853/in-typescript-what-is-the-exclamation-mark-bang-operator-when-dereferenci) in @batuhankacmaz's case are just a cue to the typescript compiler while he was debugging the issue. When I was writing the test code posted by @batuhankacmaz, as part of [Lesson 9](https://youtu.be/gyMwXuJrbJQ?t=56888), I got the same error.

My testing code in **Raffle.test.js**:

```javascript
  it("updates the raffle state, emmits and event, and calls the vrfCoordinator", async function () {
    await raffle.enterRaffle({ value: raffleEntranceFee })
    await network.provider.send("evm_increaseTime", [interval.toNumber() + 1])
    await network.provider.send("evm_mine", [])
    const txResponse = await raffle.performUpkeep("0x") // emits requestId
    const txReceipt = await txResponse.wait(1) // waits 1 block
    const raffleState = await raffle.getRaffleState() // updates state
    const requestId = txReceipt.events[1].args.requestId
    
    assert(requestId.toNumber() > 0) // <<<< ERROR LINE
    assert(raffleState == 1) // 0 = open, 1 = calculating
  })
```
This is the error the test results in:
```
1) Raffle Unit Tests
       performUpkeep
         updates the raffle state, emmits and event, and calls the vrfCoordinator:
     TypeError: Cannot read properties of undefined (reading 'toNumber')
      at Context.<anonymous> (test/units/Raffle.test.js:113:34)
```
The above error refers to the line marked in the code above. Using the **debugger** and breaking on that line, I see that in my case `txReceipt.events[1].args` is an indexed BigNumber:

```
txReceipt.events[1].args
> (1) [BigNumber, indexedRequestID: BigNumber]
```
And by accessing the 0th element of `txReceipt.events[1].args` I get '1', which I believe makes sense as the requestId.

```
txReceipt.events[1].args[0]
> 1
```

Maybe I have something incomplete in my code somewhere else, maybe the Raffle contract or the mocks. For now I can continue with `txReceipt.events[1].args[0]`, instead of `const requestId = txReceipt.events[1].args.requestId`.

**Comment by Sanchez7599** [comment]
I was having the same issue.

Fixed it by changing 
`event RequestedRaffleWinner(uint256);`
to
`event RequestedRaffleWinner(uint256 indexed requestId);` 

in my Raffle.sol.

**Comment by PatrickAlphaC** [comment]
Nice! Closing.
