### ISSUE TITLE
Hardhat shorthand not working

### ISSUE THREAD

**Issue by labib147** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#93]
![image](https://user-images.githubusercontent.com/52388164/192753764-3cfab207-f2c6-4fb8-b5f8-b6949e4f6783.png)

I installed the hardhat shorthand as shown, it does installed but when I type "hh compile" in the terminal it says "command hh not found".
Did anyone else face this? Can someone help me fix this issue please!

**Comment by RyanPaulGannon** [comment]
Have you tried installing it globally, or using npm/npx? Quite strange this!

**Comment by labib147** [comment]
yes I did try with npm but no differences whatsoever...

**Comment by RyanPaulGannon** [comment]
Have you managed to get this working yet? What else have you tried?

**Comment by MrAbuz** [comment]
Hey guys, I'm having the exact same problem. Installed hardhat-shorthand, everything seemed fine but when I tried to run 'hh compile' it sent that exact same error! 

One thing I've noted tho was that when I first tried to install 'hardhat-shorthand' I got this message:

```
warning Your current version of Yarn is out of date. The latest version is "1.22.19", while you're on "1.22.15".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
```

I'm kind of afraid of uploading it because I don't remember if we downloaded a specific version of yarn or the latest one for this course, and not looking into getting everything not working by uploading the latest version, since using 'hh' intead of 'yarn hardhat' looks like an extra :P was hoping anyone had figured it out here!!

**Comment by MrAbuz** [comment]
Hey there! 

Looks like installing hardhat-shorthand with yarn is not working properly (I was having the exact same problem as you), and the fix is to install hardhat-shorthand with npm instead, by running:
```
npm install --global hardhat-shorthand
```
Got this npm install command from the docs that Patrick provided us in the hardhat-shorthand section in our Github:
https://hardhat.org/hardhat-runner/docs/guides/command-line-completion

It worked for me, as the 'hh' command is now working. Cheers!

**Comment by s6thgehr** [comment]
Hi there,

I had to install it with admin rights to make it work with yarn.

`sudo yarn global add hardhat-shorthand`

**Comment by bvdaniel** [comment]
I had the same problem with yarn, while installing with npm worked adn now hh is recognized.

**Comment by RyanPaulGannon** [comment]
Hey, can we close this now?
